### ISSUE TITLE
TODO:SQL

### ISSUE THREAD

**Issue by LongfeiYun17** [Tokiwa-17/thssdb#1]
- [x] CREATE TABLE tableName(attrName1 Type1, attrName2 Type2,…, attrNameN TypeN NOT NULL, PRIMARY KEY(attrName1)) 
实现“NOT NULL”和“PRIMARY KEY”这两个关键字，Type为Int，Long，Float，Double，String（必须给出长度）之一。
示例: CREATE TABLE person (name String(256), ID Int not null, PRIMARY KEY(ID))
- [x] DROP TABLE tableName  删除表
- [x] SHOW TABLE tableName 展示某张表的模式信息(每一列的名字及其数据类型，格式自定)
- [x] INSERT INTO [tableName(attrName1, attrName2,…, attrNameN)] VALUES (attrValue1, attrValue2,…, attrValueN) 字符串需要用单引号包围。 示例：INSERT INTO person VALUES (‘Bob’, 15) INSERT INTO person(name) VALUES (‘Bob’)会提示字段ID不能为空
- [x] UPDATE  tableName  SET  attrName = attrValue  WHERE  attrName = attrValue
- [x] DELETE  FROM  tableName  WHERE  attrName = attrValue
- [x] SELECT tableName1.AttrName1, tableName1.AttrName2…, tableName2.AttrName1, tableName2.AttrName2,…  FROM  tableName1 [JOIN tableName2 [ON  tableName1.attrName1 = tableName2.attrName2]] [ WHERE  attrName1 = attrValue ]
## 事务
- [x] read committed 
- [x] read log

**Comment by Tokiwa-17** [comment]
- [ ] 隔离级别：read committed
- [ ] read Log
